name: StrongMCPvP
version: '1.0-SNAPSHOT'
main: pebbleprojects.strongMCPvP.PvP
api-version: 1.8
authors: [Abdelaziz]
softdepend:
  - LuckPerms
  - PlaceholderAPI
description: PvP Plugin for StrongMC
commands:
  help:
    description: Help command for PvP
  npc:
    description: Main command for PvP's NPCs
  leaderboard:
    description: Main command for PvP's Leaderboards
  setspawn:
    description: Set spawn command for PvP
  fix:
    description: Fix command for PvP
  spawn:
    description: Spawn command for PvP
  spectate:
    description: Spectate command for PvP
  scramble:
    description: Scramble command for PvP
    aliases: [sc]
  settings:
    description: Settings command for PvP