############################################################
# +------------------------------------------------------+ #
# |              Settings Configuration File             | #
# +------------------------------------------------------+ #
############################################################
npc:
  defaultName: "&5&lSettings"
  defaultSkinName: "HoneySalted"

guiName: "&5&lPlayer Settings"

